### ISSUE TITLE
Machines Deposit Into Remote Containers 1.0.0.0 occasional NullReferenceException

### ISSUE THREAD

**Issue by Plaah007** [akarnokd/ThePlanetCrafterMods#1]
Hi, not sure if this is the right place to post this.

I get the error below occasionally. Longest I've been able to play without an error is close to an hour and shortest is just a few minutes. If I save and reopen the game everything works again.

I tried just standing still and still get the error randomly.

> [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
CheatMachineRemoteDeposit.Plugin.MachineGenerator_GenerateAnObject (SpaceCraft.Inventory ___inventory, System.Collections.Generic.List`1[T] ___groupDatas) (at <2b8c386a43ec44b8bb0131f60609d3a4>:0)
(wrapper dynamic-method) SpaceCraft.MachineGenerator.DMD<SpaceCraft.MachineGenerator::GenerateAnObject>(SpaceCraft.MachineGenerator)
SpaceCraft.MachineGenerator+<TryToGenerate>d__9.MoveNext () (at <ef569e2144a04f97af2c766b55412033>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <ad199b1c67244da3a5ed230e5d202f21>:0)

**Comment by akarnokd** [comment]
Hi and thanks for reporting.

This is indeed the place to report bugs for my mods.

I'm not 100% sure what was crashing, but added a few more checks to the mod. Please find the latest version at

https://github.com/akarnokd/ThePlanetCrafterMods/releases/latest
