### ISSUE TITLE
Hide Water Mod

### ISSUE THREAD

**Issue by Richard127** [akarnokd/ThePlanetCrafterMods#10]
Having problems with this. Neither F2 or Shift-F2 is hiding the water for me. The mod is in its folder in: The Planet Crafter/BepInEx/Plugins
Any idea why or what might fix it? All other mods are working fine.

**Comment by akarnokd** [comment]
Technically it is <kbd>Left-Shift+F2</kbd> so that could be one reason.

Also it might not have loaded properly. Please post the `Player.log` in your save folder `%USERPROFILE%\AppData\LocalLow\MijuGames\Planet Crafter`.

**Comment by Richard127** [comment]
I tried both shift keys, neither worked. Here's the log... (Seem to be a lot of errors)
[Player - Copy.zip](https://github.com/akarnokd/ThePlanetCrafterMods/files/8960405/Player.-.Copy.zip)

**Comment by akarnokd** [comment]
I don't see any plugin related crashes. Let me check it ingame of mine.

**Comment by Richard127** [comment]
OK. Thanks.

**Comment by akarnokd** [comment]
It works on my end, Game 0.4.015: hides the main lake correctly. 

Which water were you trying to hide?

**Comment by Richard127** [comment]
My base was started in the Canyon, but I have a smaller base by the main lake, which didn't work either. I'll try a restart, as I believe the game caches files for quick return to game. I've attached a screenshot of the BepInEx plugins folder in case I'm missing something there
![Screenshot 2022-06-22 194505](https://user-images.githubusercontent.com/36739322/175113395-17456d68-4da1-4888-ae1e-48c80cf29b39.png)
.

**Comment by akarnokd** [comment]
Your plugins folder looks okay. Are you on Windows 11?

**Comment by Richard127** [comment]
My base was started in the Canyon, but I have a smaller base by the main lake, which didn't work either. I'll try a restart, as I believe the game caches files for quick return to game. I've attached a screenshot of the BepInEx plugins folder in case I'm missing something there.

**Comment by Richard127** [comment]
OK. After a re-start, it works in the main lakes but not in the canyon. So, just my bad luck. Thanks for your help though.

**Comment by akarnokd** [comment]
Glad it worked for you.

The mod should hide the water volumes that rise as part of the Ti and I can't remember the canyon being flooded. Could you post an image of that canyon water?

**Comment by Richard127** [comment]
Here's a couple of pics. As you can see the Canyon is full of shallow water but was dry at the start of the game. And, unfortunately, that's where a lot of resources end up after a meteor storm. Only other thing I can try is moving my rocket launcher to my lake base. I have teleporters now, so not a big problem
![20220622200230_1](https://user-images.githubusercontent.com/36739322/175117139-7c282514-8472-499d-bc4a-e68d0636ac0f.jpg)
![20220622200126_1](https://user-images.githubusercontent.com/36739322/175117143-db697281-d50a-4df4-9a4b-c6f934038e71.jpg)
.

**Comment by akarnokd** [comment]
Weird. If I toggle water, something gets hidden, but looks like there are two water volumes at those locations. Will look into it tomorrow. Thanks for the feedback.

**Comment by Richard127** [comment]
No probs. Fingers crossed for a fix. Otherwise, great mod. Thanks.

**Comment by akarnokd** [comment]
Sorry about the delay. Released 1.0.0.2 of this mod which should hide those water volumes too.

**Comment by Richard127** [comment]
Thanks, that's great. And, please, no apologies. The fact you listen and
respond is awesome.
