### ISSUE TITLE
Beacon Update

### ISSUE THREAD

**Issue by Pontiac76** [akarnokd/ThePlanetCrafterMods#100]
Seems as though you missed the update to the beacon version.  The code itself shows the diff to be 0.17, but, the version file is still at 0.16

**Comment by Pontiac76** [comment]
Ok, after looking at the version repository in the config, it shows 17, but I'm getting a popup for 16.  Probably user error.  Closing.

**Comment by akarnokd** [comment]
I'll post a new release latet today.

**Comment by Pontiac76** [comment]
Confirmed working, no more alarm.  Although the link that's presented takes me to an error page on Github.  Not a huge deal, but just putting it out into the universe.
