### ISSUE TITLE
Machine Remote Deposit Breaking Water Producers

### ISSUE THREAD

**Issue by Chloraphorae** [akarnokd/ThePlanetCrafterMods#102]
The mod broke water producers after update. Neither atm./ lake gatherers produce water.

**Comment by akarnokd** [comment]
What update?

**Comment by akarnokd** [comment]
Please post the file 
`%USERPROFILE%\AppData\LocalLow\MijuGames\Planet Crafter\Player.log`

**Comment by Chloraphorae** [comment]
I'm assuming the 1.105. This is the log after I removed all other mods to check (except ModEnabler).
[Player.log](https://github.com/user-attachments/files/16087977/Player.log)

**Comment by akarnokd** [comment]
Since the full release, the mod no longer produces water into the machine's own inventory. You have to name a container as `*WaterBottle1`.

**Comment by Chloraphorae** [comment]
Alright, thanks. I had tried to get the water to go to a specialized storage many iterations ago and could never get it to work.
