### ISSUE TITLE
Minimap enables god mode

### ISSUE THREAD

**Issue by hartzl0r3** [akarnokd/ThePlanetCrafterMods#103]
Even if the settings are turned off in the config or mod manager for every option; once minimap is loaded you get infinite O2 and your health (hunger)/thirst do not reduce.

**Comment by akarnokd** [comment]
Sounds like you turned on `PhotographMap` settings which is not meant for normal use.

**Comment by hartzl0r3** [comment]
Thanks mate, after loading and unloading, its finally normal. Thank you kindly
