### ISSUE TITLE
Minor Issue with Planet Crafter-(Cheat) Asteroid Landing Position Override

### ISSUE THREAD

**Issue by Brett-Grat** [akarnokd/ThePlanetCrafterMods#104]
Recently set up a new base up in the Ice Field and discovered that when I run "(Cheat) Asteroid Landing Position Override" with the default setting of 100 units (East), none of the meteor showers appear (or maybe they are wrapping around to the bottom of the map?).
My base is at 2150:80:730 and my launch pad is at 2114:108:715.
Once I changed the setting to -100, everything worked as expected. Don't know if this is a 'bug' or just needs a comment in the readme warning of the behaviour.
Thanks in advance,
Brett Bridger

**Comment by akarnokd** [comment]
Some locations are excluded by the game and won't drop meteors there. Consider experimenting a bit and picking an absolute coordinate.
