### ISSUE TITLE
Wreck Map Mod Cannot Distinguish Between Two (or more?) Wrecks Generated When Traveling Through The Portal Generator

### ISSUE THREAD

**Issue by J-SoG-YK** [akarnokd/ThePlanetCrafterMods#106]
Upon traveling through the Portal Generator, I found there were two wrecks generated.  But the Wreck Map Mod treats both Wrecks as the same.  Essentially overlapping the first wreck's map over the second.  This makes the Wreck Map practically useless in the second wreck.  Since I have absolutely no idea how the Wreck Map does what it does, I really don't know if it's possible to distinguish one wreck from another.  If a separate map, for each wreck generated, cannot be created per Wreck Map.  Might it be possible to reset the map per Wreck Map?

**Comment by akarnokd** [comment]
Currently, there is no way to distinguish between multiple wrecks. Not sure when it can be fixed.

Use <kbd>Ctrl+L</kbd> to clear the wreck map.

**Comment by J-SoG-YK** [comment]
That's fine by me.  Sorry, I missed the documentation in the README, I went looking in the wiki instead.  I should probably tweak the settings for the custom scrollbar extension I use.  It currently makes it hard to see the length of a page sometimes.  I didn't realize the length of the README and didn't 'read' it in full.

Thank you.
