### ISSUE TITLE
InventoryStacking

### ISSUE THREAD

**Issue by Rebraxin** [akarnokd/ThePlanetCrafterMods#107]
Hi, im trying to use use InventoryStacking and i noticed that the backpack didnt stack.

Versions:
- Game: v1.105
- BepInEx: v5.4.23.2
- ThePlanetCrafterMod: v517 and.

I have run debug mode true to check logs, and nothing wrong so far. I'll share with you what i have.

```
[Error  :   BepInEx] Unable to start Unity log writer
[Message:   BepInEx] BepInEx 5.4.23.2 - Planet Crafter (7/26/2024 7:32:55 AM)
[Info   :   BepInEx] Running under Unity v2023.2.19.9814680
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [(Cheat) Inventory Stacking 1.0.1.32]
[Info   :(Cheat) Inventory Stacking] Plugin is loaded!
[Info   :(Cheat) Inventory Stacking] Mod akarnokd.theplanetcraftermods.cheatcraftfromnearbycontainers not found.
[Info   :(Cheat) Inventory Stacking] Mod valriz.theplanetcrafter.storagebuffer not found.
[Message:   BepInEx] Chainloader startup complete
```

Have i done something wrong ?

**Comment by akarnokd** [comment]
Check then configuration if you have `StackBackpack = false` somehow.

**Comment by Rebraxin** [comment]
Ty for repply :)

I have try to reinstall everything (Game, BepInEx, Mods)
Still the same result.

here is  extract from my config file :

```
...

## Should the player backpack stack?
# Setting type: Boolean
# Default value: true
StackBackpack = true

...
```

If i can do anything to help to solve this, just let me know

**Comment by akarnokd** [comment]
Install BepInEx 5.4.22 and see if that works

**Comment by Rebraxin** [comment]
Nope, same problem

![image](https://github.com/user-attachments/assets/3ddbc08b-4852-4d63-ba5d-e87ad1dea128)

**Comment by akarnokd** [comment]
Oh, you misunderstand what the mod does.

It allows you to have multiple of the same item in your backpack, not allowing you to equip multiple backpacks.

**Comment by Rebraxin** [comment]
And this is the moment i realize how dumb i am :D

Sorry, i tough i was able to equip multiple backpack to increase inventory size

My bad tho
