### ISSUE TITLE
Suggestion: auto set storage name from item in chest

### ISSUE THREAD

**Issue by stephen-dahl** [akarnokd/ThePlanetCrafterMods#110]
Add an option to Auto Store mod that sets the name of the storage to the first item placed in it.
Only set the name if the name is currently empty.

This would greatly simplify configuring storage early game since i wont have to go hunt down item ids

**Comment by akarnokd** [comment]
Unfortunately, there is no good way to capture this user intent as it could arbitrarily rename containers not intended for such storage.
