### ISSUE TITLE
Request: Don't pull last item from container

### ISSUE THREAD

**Issue by LexManos** [akarnokd/ThePlanetCrafterMods#118]
If possible can you make the Craft From Nearby Containers not use the last item in the chest.
It causes issues with the auto-store functionality (even if i set store by name and the prefix to empty)
I also use [StorageDisplay](https://www.nexusmods.com/planetcrafter/mods/91) to show the item icon and it's nice seeing chests by icon instead of name.

**Comment by akarnokd** [comment]
I can't. It would require rewriting all of the game's inventory use.
