### ISSUE TITLE
Machines Deposit Into Remote Containers MOD don't work with Ore Crusher 

### ISSUE THREAD

**Issue by realhagie** [akarnokd/ThePlanetCrafterMods#121]
The Mod "Machines Deposit Into Remote Containers" don't work with Ore Crusher. It looks like the machine isn't recognized at all, I can't see any information in the debug log.

**Comment by akarnokd** [comment]
It is not supported yet. Don't know yet when it will be supported.

**Comment by realhagie** [comment]
Thanks for the response and for your work !

**Comment by akarnokd** [comment]
Implemented in v1.0.0.28
