### ISSUE TITLE
Mods and Multiplayer

### ISSUE THREAD

**Issue by Jayshua83** [akarnokd/ThePlanetCrafterMods#125]
Are there any of your mods that we shouldn't both run in MP as only the host would need it?

My wife will get red screen crashes and then when she crashes out of the game it crashes my game and I am the HOST!

So weird!

Is there log files somewhere we can look at or post too see what mod might be causing it?

**Comment by akarnokd** [comment]
The only multiplayer-incompatible mod of mine is *Technician's Exile* which none of you should run.

The general rule is to everyone have the same mods and same settings. Some mods disable themselves when run on the client, some mods don't fully work on the client. None of them should cause red screen crashes.

[Here is a table for mod compatibility](https://planet-crafter.fandom.com/wiki/Modding#Multiplayer_Compatibility_Matrix)

Please post the file `%USERPROFILE%\AppData\LocalLow\MijuGames\Planet Crafter\Player.log` from the host and the client after you encounter a red crash. Note though that there are vanilla bugs that can cause such crashes too.

**Comment by Jayshua83** [comment]
Here are the logs and DMPs files if needed!

Thanks!

[host_crash.dmp](https://github.com/user-attachments/files/17589757/host_crash.dmp)
[Host_Player.log](https://github.com/user-attachments/files/17589760/Host_Player.log)

[client_crash.dmp](https://github.com/user-attachments/files/17589758/client_crash.dmp)
[Client_Player.log](https://github.com/user-attachments/files/17589759/Client_Player.log)

**Comment by akarnokd** [comment]
You both have graphics driver related crashes for one. Please see the [Steam Troubleshooting FAQ](https://steamcommunity.com/app/1284190/discussions/0/4345481341076503754/) for possible resolutions.

Otherwise, looks like a red errors are due to desyncs.

**Comment by Jayshua83** [comment]
Ok. We'll keep checking things out...

We had issues last time we played but they eventually settled.

I think part of it is related to ReShade! TPC doesn't work well all the time with ReShade for some reason. Most other unity games work pretty well with it! :(
