### ISSUE TITLE
Bug or Feature with Auto Harvest?

### ISSUE THREAD

**Issue by Brett-Grat** [akarnokd/ThePlanetCrafterMods#126]
Don't know if this was by design, but. With auto-harvest on, the contents of chests, etc, are NOT harvested, but the new geodes in The Planet Crafter - Humble are.
Thanks in advance.

**Comment by akarnokd** [comment]
Chest contents are not considered by design.

**Comment by Brett-Grat** [comment]
Sorry, I was obviously not clear. Yes, I expected chest contents not to be harvested, but I was surprised when I found geode contents ARE harvested. This seems to be inconsistent, to exclude one, but not the other. After going through the geode area with autoharvest on, I find that EVERY geode is now empty.

**Comment by akarnokd** [comment]
Geodes are not containers. The mineral is in the world, only obstructed by the geode around it. Can't do anything about it.
