### ISSUE TITLE
Request: have auto-save, initiate a save every X minutes.

### ISSUE THREAD

**Issue by Layarion** [akarnokd/ThePlanetCrafterMods#14]
Would be a life saver if the auto-save mod could be told to make a save every 10 minutes or something in the config.

**Comment by akarnokd** [comment]
I wouldn't conflate this mod with it. Maybe someone on the [Discord](https://discord.com/channels/635441508694097921/882722354722127882) would be interested in creating a separate mod.

**Comment by Layarion** [comment]
Ok i'll check it out.

**Comment by akarnokd** [comment]
Hi. I decided to create the mod **(Save) Auto Save**. You can find it among the recent releases.
