### ISSUE TITLE
CheatMinimap key remaping in config does nothing

### ISSUE THREAD

**Issue by esvarc** [akarnokd/ThePlanetCrafterMods#22]
Actually setting ToggleKey = N in akarnokd.theplanetcraftermods.cheatminimap.cfg is not reflectd in game. I put there M, but it still use default N.

```
## Settings file was created by plugin (Cheat) Minimap v1.0.0.17

...

## The key to press to toggle the minimap
# Setting type: String
# Default value: N
ToggleKey = M
```

**Comment by esvarc** [comment]
Nice to have minimap not only verticaly configurable, but to be able horizontally placed would be great addition. BTW all plugins it is great job done.

**Comment by akarnokd** [comment]
Thanks for reporting. Fixed the shortcut key issue and added `MapLeft` so you can now position it freely.
