### ISSUE TITLE
cheatminimap - photograph map unable to get out

### ISSUE THREAD

**Issue by lessmarble** [akarnokd/ThePlanetCrafterMods#28]
using your minimap mod,  works great

i seen an option for photograph map (hit U) in cfg file so gave it a try.
was unable to escape from the map using u again nor esc or any other way i thought reasonable.
now my char is stuck in a perpetual movement rearwards.  
I can no longer play the game.  this persists after exiting the game as well..
( i even removed the plugin and cfg file, still was stuck)

**update...
ok, finally got out of it,  it took a death to make it happen...   i could only hold myself in place by using the space bar**

also, would be interested in being able to have markable points, so i can mark where i put down a building,
(hit a key and current location drops a dot and saves it, hit another key and closest dot gets removed)  
hopefully something simple like this can be done

thanks

**Comment by akarnokd** [comment]
The <kbd>U</kbd> mode is not for gameplay or for players. I use it to take a photo of the entire map and it leaves the game in an unplayable state. Don't save and use <kbd>Alt+F4</kbd> to quit.

I don't want to have the minimap bloated with icons so I won't add new stuff to it for now.

**Comment by lessmarble** [comment]
hey David, 
thanks for the reply. 
might want to mention not to use it or remove the photographmap defined entry in the cfg file.  
I thought I had lost that play thru until I died and all was back to normal. 

thanks for all the great mods.  wish I could program these things.. 

⁣Get TypeApp for Android ​

On Oct 23, 2022, 1:08 AM, at 1:08 AM, David Karnok ***@***.***> wrote:
>The <kbd>U</kbd> mode is not for gameplay or for players. I use it to
>take a photo of the entire map and it leaves the game in an unplayable
>state. Don't save and use <kbd>Alt+F4</kbd> to quit.
>
>I don't want to have the minimap bloated with icons so I won't add new
>stuff to it for now.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/akarnokd/ThePlanetCrafterMods/issues/28#issuecomment-1288032269
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>
