### ISSUE TITLE
Auto Harvest

### ISSUE THREAD

**Issue by Taragonra** [akarnokd/ThePlanetCrafterMods#29]
I can't seem to get the auto harvest mod to work. I'm trying to get it to harvest algae. I've downloaded it to the plugin folder and named the container correctly, but it's not grabbing the algae. Is there a range limit?

**Comment by akarnokd** [comment]
It's unlimited. Do you have any other mods?

If not, you installed BepInEx incorrectly.

**Comment by Taragonra** [comment]
I have your item stacking mod and a few others that work just fine.

**Comment by akarnokd** [comment]
Algae grows really slowly. 

If you reload your save, do you get the algae deposits?
How did you name your containers?

**Comment by Taragonra** [comment]
Reloading the save did it. There also might have been an invisible space in the container name, I cut and paste the first time.
