### ISSUE TITLE
Mutliplayer Mod

### ISSUE THREAD

**Issue by karlbibby** [akarnokd/ThePlanetCrafterMods#35]
After updating to the fish update the host ip stays saying checking and never gives an IP.

On the client you cant click the join as buddy button either.

**Comment by akarnokd** [comment]
Did you update the mod?

**Comment by karlbibby** [comment]
yes i deleted all the mods and just installed the multiplayer one. It is happening on my pc and my friends pc who was hosting the game.

**Comment by karlbibby** [comment]
In the log it shows this

Last Seen: 01/03/2023 18:17:48
[Info   :(Feat) Multiplayer] Begin Get External IP
[Info   :(Feat) Multiplayer] External IP = x.x.150.211 (blanked for privacy)
[Info   :(Feat) Multiplayer] Current Mapping = Tcp 22526 --> 192.168.0.172:22526 (The Planet Crafter Multiplayer)

but in game it says checking and even I enter the IP shown there in the config and click the join with dude nothing happens.

**Comment by akarnokd** [comment]
Did you both edit the BepInEx.cfg as instructed?

**Comment by karlbibby** [comment]
yeah, it was all working before the latest update.

**Comment by akarnokd** [comment]
Please update your mod again to today's version.

**Comment by karlbibby** [comment]
I just updated to todays version and the ip is showing correctly. I cannot test the connectivity currently as my coop partner is not around but its looking positive.

**Comment by karlbibby** [comment]
tested tonight and its working correctly again. thank you very much :)
