### ISSUE TITLE
Drones not working with Multiplayer

### ISSUE THREAD

**Issue by karlbibby** [akarnokd/ThePlanetCrafterMods#37]
I know this is a new feature in this update so I am guessing that it will need work but the issues we have spotted are

1. When setting drones supply/demand this is not synced between the host and client.

2. The drones dont start flying and just sit in the drone controller even when either host/client set their supply/demand.

**Comment by akarnokd** [comment]
Hi.
Please make sure you both have the latest mod version.

Please load the attached world, try modifying the logistics settings and see if the drones operate or not.

[Stacking-Drone-Test.zip](https://github.com/akarnokd/ThePlanetCrafterMods/files/10887541/Stacking-Drone-Test.zip)

If not, please post the `Player.log` of both host and client, `Player_Host.log` and `Player_Client_<user>.log`.

**Comment by MiniMeOSc** [comment]
Hi.
A friend and I observed similar behavior. We have been playing with version 0.2.0.19 until we finally unlocked drones. We have both tried setting supplies and demands, however the drones didn't start. When the host played alone the drones seemed to work, but when the client joined it seemed they stopped working.

When the client sets supplies and demands, the host can see those in the storage chests:
![supply](https://user-images.githubusercontent.com/29428370/222929003-6e1b6e1d-4576-4b97-9f4e-0b02d34c3d3c.jpg)
![demand](https://user-images.githubusercontent.com/29428370/222929010-6d181438-a090-4c44-b584-5a04249f31e6.jpg)

However the host can not see them in the drone station:
![host_drone_station](https://user-images.githubusercontent.com/29428370/222929038-0761252b-73c5-47d1-bf62-060e01ea846c.jpg)

The client can see the supplies and demands in the drone station, but the drones remain idle (no drones listed for supply or demand):
![client_drone_station](https://user-images.githubusercontent.com/29428370/222929048-ab69bab4-22fa-4795-a129-ed5f708d3b4a.jpg)

We collected these logs with version 0.2.0.19, but once we saw you released a new version just a few minutes ago we tested it again, however the behavior is still the same. The game unfortunately doesn't create a Player_Host.log file.
[Logs-drones-multiplayer.zip](https://github.com/akarnokd/ThePlanetCrafterMods/files/10889684/Logs-drones-multiplayer.zip)

**Comment by akarnokd** [comment]
Thanks. I'll look into it but might not get a fix out before late Monday.

**Comment by akarnokd** [comment]
I put up a new version in [v202](https://github.com/akarnokd/ThePlanetCrafterMods/releases/tag/v202). Please try it and let me know if the drones still stop working when the client joins.

**Comment by MiniMeOSc** [comment]
Thank you very much for the quick reaction. We've just tested v204. The drones now appear to be working.

**Comment by karlbibby** [comment]
Sorry we didnt get time to test busy weekened. Just loaded with latest mod and drones are working. There seem to be occasonal sync issues where you need to set the supply/demand more than once as the client but other than that its working and drones are flying.

**Comment by akarnokd** [comment]
Thank you for the feedback and confirmation.

It could be the 3 second periodic sync that's messing with the supply/demand on the client. I'll look into it tomorrow.

**Comment by akarnokd** [comment]
Okay. Uploaded a new version which should fix that supply/demand setting problems on the client. Please let me know if it works for you.
