### ISSUE TITLE
When the game is set to CJK language, part of the console output will not be displayed correctly

### ISSUE THREAD

**Issue by KagurazakaNyaa** [akarnokd/ThePlanetCrafterMods#39]
The default font `arial.ttf` used by the mod cannot display CJK characters correctly. Can the font be configured to support the display of CJK characters?
For example, we can add a configuration `FontName`, string type, the default value is `arial.ttf`, and then replace the hard code below with this configuration variable.
https://github.com/akarnokd/ThePlanetCrafterMods/blob/fd2f247fa1723460c30b079fe925d8c9be596b6d/FeatCommandConsole/Plugin.cs#L118-L126

```cs
fontName = Config.Bind("General", "FontName", "arial.ttf", "The font name in the console");

if (fp.ToLower().Contains(fontName))  //L120
```

**Comment by akarnokd** [comment]
Sure. Will post an update shortly.

**Comment by akarnokd** [comment]
Done in 1.0.0.11.
