### ISSUE TITLE
request

### ISSUE THREAD

**Issue by wackoamd1** [akarnokd/ThePlanetCrafterMods#4]
akarnokd since u make these great Qol mods ,
 is there any chance u can or will make a mod to configure the speed at which food water and oxygen goes down.?

i know there is advanced mode by skrwoor but that does too much different stuff.

thanks in advance if u are willing to make such Qol mod

**Comment by akarnokd** [comment]
Not likely, sorry. Perhaps someone else would do it [on the modding channel](https://discord.com/channels/635441508694097921/882722354722127882)?
