### ISSUE TITLE
Multiplayer Mod Dedicated Servers (Headless)

### ISSUE THREAD

**Issue by TheFlash787** [akarnokd/ThePlanetCrafterMods#42]
Hey there,

I love The Planet Crafter and I plan on using the Multiplayer mod so that I can play with my friends.

I'm wondering, is it possible to run a headless client of the game with the Multiplayer mod installed so me and my friends can connect to the server without me having to be online 24/7, a bit like Rust/ARK/Minecraft/Satisfactory, etc?

If it's not currently possible, is this something planned in the project?

Thanks!

**Comment by akarnokd** [comment]
Hi. 

It is currently not possible and is not planned. It would require duplicating almost the entire game's logic, which is a huge undertaking, especially for free.
