### ISSUE TITLE
Use .prop files for game paths

### ISSUE THREAD

**Issue by WildCard65** [akarnokd/ThePlanetCrafterMods#5]
Right now, every project uses 2 hard-coded sets of paths for finding the game's files, this is not a good idea.
The first path it tries assumes that the builder uses the default Steam library path while the other is unique to your system only.

The easiest solution would be a "Directory.Build.props" at the solution level that imports a props file (if it exists) for game install dir or default to the Steam default path.

Note: I'm currently working on a solution to this issue.

**Comment by akarnokd** [comment]
I'm not sure you can do it on your end and verify it worked.

I reworked the directory properties and posted the changes. Now you can edit [solution_private.targets](https://github.com/akarnokd/ThePlanetCrafterMods/blob/main/solution_private.targets) on your end.

**Comment by WildCard65** [comment]
I managed to create something that will overall rude the total size of this project by reducing a lot of duplications. And it compiles & copies properly.

**Comment by akarnokd** [comment]
Please leave the tidying to me.

**Comment by WildCard65** [comment]
@akarnokd Already sent a PR, #6
