### ISSUE TITLE
MP mod - Some items picked up from the world by clients become "sticky"

### ISSUE THREAD

**Issue by chambm** [akarnokd/ThePlanetCrafterMods#53]
Thanks for the great mod! I want to report a bug. It has happened with several objects picked up from chests or in shipwrecks, and most recently the generic frog eggs picked up from the ponds. I am playing as a client connected to another host computer on the LAN. When I drop these sticky objects they teleport back to my inventory in a second or two. The same thing happens when I try to incubate with the eggs, except in that case the eggs usually become "locked" in my inventory after being teleported. The same thing happens when I try to destroy the eggs: they get teleported back to my inventory. I don't think the problem happens for the host. If I drop the eggs and the host picks them up before they teleport, that does seem to fix the problem (they stop teleporting).

Only 2 other mods:
Better jetpack 0.2.0
UIStackInRangeList 1.0.0.2

FeatMultiplayer 0.2.0.42

**Comment by akarnokd** [comment]
There is a long standing respawn and duplication bug with the vanilla game. I've tried to fix that but never succeeded.

If you experience this, the host has to restart the session and the duplicates will be erased.

**Comment by chambm** [comment]
Is the bug you're referring to limited to only objects picked up from the world? Because that's the only time I've seen this stickiness. It doesn't usually cause duplication: the sticky item "teleports" back to my inventory instead of getting duplicated. Restarting my client doesn't fix it, but I'll try restarting the host next time and see if that fixes it.

**Comment by akarnokd** [comment]
Seeds, flowers, rocket engines, frog eggs, anything you'd pick up from the world or wrecks can be a duplicate which confuses the game.

**Comment by chambm** [comment]
OK I'll treat it as a known issue then and have my host pick up all the world objects. Thanks!

**Comment by akarnokd** [comment]
Multiplayer mod is now discontinued.
