### ISSUE TITLE
Can not move Item from Chest

### ISSUE THREAD

**Issue by djdanby** [akarnokd/ThePlanetCrafterMods#56]
Hello ;)

Problem: I have in one of my cabinets, Generic Frog Eggs inside, and I can not take them out of the cabinet. And I can't dismantle the cabinet because of this. I use your StackItem mod. I can add to the stack eggs, more eggs. But as soon as I want to take them all out again, there are always 2 left that I can't pick up.
Normally I would have used the autocrafter to get the eggs out of the cabinet, but the recipe is missing in the autocrafter. Now I don't know if it's the stack mod or the game itself.

I use the latest game version and the latest game mods from today.

What do you need to find the error?
Player log or dev log? Or Save Game? Or everything?

Active Mods:
- AutoConsume
- Minimap
- InventoryStacking
- FixUnofficialPatch
- AutoBackup
- QuickSave
- PinRecipe
- SaveonQuit
- SortSaves

**Comment by akarnokd** [comment]
There is a vanilla respawn bug that creates duplicates of items which can not be in the same inventory. You have to use up, shred or lose the duplicate(s). *Not a bug with any mods.*

**Comment by djdanby** [comment]
Ok. Is there a way to remove the cabinet inclusive items? Any mod or something?

**Comment by akarnokd** [comment]
What do you mean by "cabinet inclusive items"?

**Comment by djdanby** [comment]
Problem has probably just been solved. I walked around the map less, and just went back to the cabinet. And suddenly I was able to pick up the items after all. 
I meant that I can remove the cabinet, including the items that are in it. The items are not stuck in my inventory, but in the cabinet.
But has now settled for the time being. Somehow the game has regulated the itself. However^^I
