### ISSUE TITLE
Feature Request Automate Incubator

### ISSUE THREAD

**Issue by djdanby** [akarnokd/ThePlanetCrafterMods#58]
Hi.

Is there a way to add inventory stacking to Incubator or get all items via drones from chests? The Incubator can not consume Generic Frog Eggs via Drones, but u have a made an Auto DNA Mod.  Would be cool when we can automate the Frog recipes. :)

**Comment by akarnokd** [comment]
Auto Sequence DNA works fine with frog eggs. You need to craft the generic eggs manually once and keep it somewhere safe. It is a vanilla drone bug/issue.

**Comment by djdanby** [comment]
Ah ok. Damn Bugs^^. Thanks for Info :)
