### ISSUE TITLE
(UI) Craft Equipment Inplace conflict with skrwoor creative mode

### ISSUE THREAD

**Issue by xtianpu** [akarnokd/ThePlanetCrafterMods#61]
Hello, as the title says, when in Craft Building UI with [skrwoor creative mode](https://www.nexusmods.com/planetcrafter/mods/2/) we can build anything without any resources, but looks like (UI) Craft Equipment Inplace is forbid it so when we click the building on the UI it doesn't show any ghost building.

**Comment by akarnokd** [comment]
I don't understand. Craft Equipment Inplace has nothing to do with buildings.

Please provide the detailed reproduction steps, saves and the `Player.log` from `%USERPROFILE%\AppData\LocalLow\MijuGames\Planet Crafter` after you tried reproducing the issue.

**Comment by xtianpu** [comment]
Oops sorry! Just found out https://www.nexusmods.com/planetcrafter/mods/2/ was the problem, looks like it's not updated and also cut half of 60 FPS
