### ISSUE TITLE
Mod Request - Inventory Statistics Screen

### ISSUE THREAD

**Issue by tbird68** [akarnokd/ThePlanetCrafterMods#68]
First, let me thank you for your excellent QOL mods. Have made the game less grindy. Much appreciated.

Now the mod request - is it possible to create a screen that shows inventory contents - ie, Total Iron, Cobalt, Obsidian, etc. for all ores, plants, & created items? Would certainly speed up item collection knowing on one screen what you have so you know what you need without having to check dozens of storage individually.

Thanks for your consideration.

**Comment by akarnokd** [comment]
Possible, but not interested. 

Try the [official game Discord's](https://discord.gg/9YPjJ3C) #modding channel - a few recend modders might be willing to do such a mod.
