### ISSUE TITLE
Mod Request/help

### ISSUE THREAD

**Issue by DeForestDiamond** [akarnokd/ThePlanetCrafterMods#82]
Good day!

I was wondering if you knew how to or if you would be willing to make Crazymetal's EquipmentExtend mod work again. I know nothing of modding so I don't know how difficult of a request I have made. 

Either way, thank you and thank you for all the awesome mods!
Mike

**Comment by akarnokd** [comment]
Hi. 

I'm sorry I can't redo his.

1.0 made his changes very difficult to reimplement and also it would conflict with some of my existing mods.

**Comment by DeForestDiamond** [comment]
Thank you and no worries. I really appreciate all your effort!
