### ISSUE TITLE
Item Stacking Enhancement

### ISSUE THREAD

**Issue by Pontiac76** [akarnokd/ThePlanetCrafterMods#99]
LOVE this particular mod.  However, it's not a best fit for all situations.

If a storage container doesn't have [?] (? being an integer) at the beginning of its name, it uses the default stack size defined in the config for that container.  However, if there is a [?], then the max stack size should be set to that.

The reason why is that I currently have my stack size set to 64 (Nod to minecraft), but, I don't need that kind of stack in all places, like, a cargo that contains just my food, or, a particular chest set for auto crafting items, etc.

**Comment by akarnokd** [comment]
Not planning on chaning the mod behavior.
